import { cloud, configured, rpc, importLegacy } from './cloud.js';
import { esc, money, dateLabel, normalize, addDays, period, totals, csv, anniversaryReached } from './domain.js';
import { demoRpc } from './demo.js';

const $ = id => document.getElementById(id), app = $('app');
let state, demo=false, demoRole='owner', route='home', routeArgs={}, sequence=0, recovery=false;
const owner=()=>state?.me.role==='owner';
function applyBrand(name=window.BARBER_CONFIG?.shopName || 'Barbearia'){
    document.title=name;
    document.querySelectorAll('.marca-nome').forEach(el=>{el.textContent=name;});
    document.querySelector('.login-apresentacao')?.setAttribute('aria-label',name);
    $('marcaHome').setAttribute('aria-label',name+', ir para início');
    document.querySelector('.login-rodape').textContent=name;
    document.querySelector('.app-footer > span').textContent=name;
}
const call=(action,payload)=>demo?demoRpc(action,payload,demoRole):rpc(action,payload);
const icons={cut:'<circle cx="6" cy="18" r="3"/><circle cx="18" cy="18" r="3"/><path d="m8 16 11-13M16 16 5 3"/>',people:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-2a6 6 0 0 1 12 0v2M16 5a3 3 0 0 1 0 6M18 15a5 5 0 0 1 3 4v2"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18"/>',money:'<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20M6 15h3"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.cut}</svg>`;
let noticeTimer;
function notify(message,error=false){clearTimeout(noticeTimer);$('statusMessage').textContent=message;$('statusMessage').className='status-message '+(error?'status-error':'status-success');noticeTimer=setTimeout(()=>{$('statusMessage').textContent='';},error?15000:8000);}
function errorMessage(error){
    if(!navigator.onLine)return 'Sem conexão. Seu formulário foi mantido; reconecte-se e tente novamente.';
    const msg=error?.message||'Não foi possível concluir. Tente novamente.';
    if(/invalid login credentials/i.test(msg))return 'E-mail ou senha incorretos.';
    if(/email not confirmed/i.test(msg))return 'Confirme o e-mail recebido antes de entrar.';
    if(/fetch|network/i.test(msg))return 'Não foi possível conectar. Confira sua internet e tente novamente.';
    return msg;
}
function breakdown(rows,key,title){
    const grouped=new Map();for(const row of rows.filter(s=>!s.canceled)){const name=row[key]||'Não informado';if(!grouped.has(name))grouped.set(name,[]);grouped.get(name).push(row);}
    return `<section><h3>${title}</h3>${[...grouped.entries()].map(([name,items])=>{const t=totals(items);return `<div class="registro record-main"><div><strong>${esc(name)}</strong><small>${t.count} atendimento${t.count===1?'':'s'}</small></div><div class="record-amount"><strong>${money(t.amount)}</strong><small>Comissão ${money(t.commission)}</small></div></div>`;}).join('')||empty('Sem registros.')}</section>`;
}
const field=(id,label,type='text',value='',extra='')=>`<div class="form-field"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" value="${esc(value)}" ${extra}></div>`;
const select=(id,label,options,value='')=>`<div class="form-field"><label for="${id}">${label}</label><select id="${id}" name="${id}">${options.map(([v,t])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`).join('')}</select></div>`;
const button=(text,action,args='',kind='botao-secundario')=>`<button type="button" class="${kind}" data-action="${action}" data-id="${esc(args)}">${text}</button>`;
const empty=text=>`<p class="vazio">${text}</p>`;
const submit=text=>`<button type="submit" class="botao-principal">${text}</button>`;
function panel(title,subtitle,content){return `<section class="painel"><div class="page-title"><div><h2 tabindex="-1">${esc(title)}</h2><p>${esc(subtitle)}</p></div>${button('← Início','home','','link-texto')}</div>${content}</section>`;}
function metrics(rows){const t=totals(rows);return `<div class="cards metric-cards"><div class="card"><small>Atendimentos</small><strong>${t.count}</strong></div><div class="card"><small>Faturamento</small><strong>${money(t.amount)}</strong></div><div class="card"><small>Comissões</small><strong>${money(t.commission)}</strong></div><div class="card"><small>${owner()?'Após comissões':'Média por atendimento'}</small><strong>${money(owner()?t.net:t.average)}</strong></div></div>${owner()?'<p class="hint">Após comissões não representa lucro: outras despesas não estão incluídas.</p>':''}`;}
function download(name,content,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function serviceRows(rows,canCancel=false){return rows.length?`<div class="records">${rows.map(s=>`<article class="registro ${s.canceled?'canceled':''}"><div class="record-main"><div><strong>${esc(s.client_name||s.barber_name)}</strong><p>${esc(s.service_name)}</p><small>${dateLabel(s.day)} · ${esc(s.barber_name)} · ${esc(s.payment)}</small></div><div class="record-amount"><strong>${money(s.amount)}</strong>${s.commission!==undefined?`<small>Comissão ${money(s.commission)}</small>`:''}</div></div>${s.canceled?`<p class="hint">Cancelado: ${esc(s.cancel_reason)}</p>`:canCancel&&owner()?button('Cancelar registro','cancel',s.id,'botao-excluir'):''}</article>`).join('')}</div>`:empty('Nenhum atendimento encontrado neste período.');}
function bindForm(id,handler){$(id)?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;if(form.dataset.busy)return;form.dataset.busy='true';const btn=form.querySelector('[type=submit]'),previous=btn.textContent;btn.disabled=true;btn.textContent='Salvando…';try{await handler(Object.fromEntries(new FormData(form)),form);}catch(error){notify(errorMessage(error),true);}finally{delete form.dataset.busy;btn.disabled=false;btn.textContent=previous;}});}
async function save(action,payload,next=route,args=routeArgs){await call(action,payload);if(await go(next,args))notify('Salvo com sucesso.');else notify('O registro foi salvo, mas não foi possível atualizar a tela. Use Atualizar antes de tentar novamente.',true);}
function showLogin(){sequence++;state=null;app.innerHTML='';$('appPrincipal').style.display='none';$('telaLogin').style.display='flex';$('loginSenha').value='';$('loginEmail').focus();}
async function go(page='home',args={}){
    const current=++sequence;route=page;routeArgs=args;app.setAttribute('aria-busy','true');
    try{
        const next=await call('state');if(current!==sequence)return;state=next;applyBrand(state.shop.name);
        $('telaLogin').style.display='none';$('appPrincipal').style.display='block';$('headerPerfil').textContent=owner()?'Administrador':state.me.name;
        $('demoBanner').hidden=!demo;$('demoBanner').innerHTML=`<span><strong>Demonstração</strong> · Dados fictícios, somente consulta.</span>${button(demoRole==='owner'?'Ver como barbeiro':'Ver como dono','demoRole','','link-texto')}${button('Sair da demonstração','logout','','link-texto')}`;
        document.querySelectorAll('.menu-inferior button').forEach(b=>{const selected=b.dataset.page===page||(page==='newService'&&b.dataset.page==='services')||(page==='history'&&b.dataset.page==='clients');b.classList.toggle('ativo',selected);if(selected)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
        const views={home,services,clients,history,newService,goals,team,catalog,account,audit};
        if(['team','catalog','audit'].includes(page)&&!owner())throw new Error('Acesso reservado ao dono.');
        await (views[page]||home)(args,current);if(current!==sequence)return;
        window.scrollTo({top:0,behavior:'instant'});app.querySelector('h2[tabindex],h1')?.focus({preventScroll:true});
        $('syncTime').textContent=`Atualizado às ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`;
        return true;
    }catch(error){if(current!==sequence)return;notify(errorMessage(error),true);if(!state||/acesso ainda|confirme seu e-mail|entre na sua conta|JWT|session/i.test(error?.message||''))showLogin();}
    finally{if(current===sequence)app.removeAttribute('aria-busy');}
}
function home(){
    const t=totals(state.services.filter(s=>s.day===state.today&&!s.canceled)),recent=state.services.filter(s=>!s.canceled).slice(0,4);
    const shortcuts=[['services','calendar','Atendimentos','Consulte seus registros'],['clients','people','Clientes','Conheça cada história'],...(owner()?[['team','cut','Profissionais','Cuide da sua equipe'],['services','money','Financeiro','Acompanhe os resultados']]:[])];
    app.innerHTML=`<div class="dashboard-home"><div class="dashboard-intro"><div><span class="eyebrow">${owner()?'PAINEL DO DONO':'ESPAÇO DO BARBEIRO'}</span><h1 tabindex="-1">${owner()?'Seu painel':'Olá, '+esc(state.me.name.split(' ')[0])}</h1></div><span class="dashboard-data">${icon('calendar')}${dateLabel(state.today)}</span></div>
    <section class="banner-dashboard"><div class="banner-conteudo"><span class="eyebrow">PRECISÃO. ESTILO. IDENTIDADE.</span><h2>Tradição no corte.<br><em>Evolução na gestão.</em></h2><p>Seu talento merece uma rotina à altura.<br>Cuide de cada atendimento, do início ao fim.</p>${button(icon('cut')+' Registrar serviço ↗','newService','','botao-principal')}</div><span class="banner-selo">CUIDADO EM CADA DETALHE</span></section>
    <section class="resumo-grid" aria-label="Resumo de hoje">${[['cut','Atendimentos hoje',t.count],['money','Faturamento hoje',money(t.amount)],['target','Média por atendimento',money(t.average)]].map(([i,label,value])=>`<div class="resumo-item"><span class="resumo-icone">${icon(i)}</span><div><small>${label}</small><strong>${value}</strong><p>${owner()?'Visão da barbearia':'Seus atendimentos'}</p></div></div>`).join('')}</section>
    <section><div class="secao-cabecalho"><h2>Tudo ao seu alcance</h2><small>Seu dia, bem organizado.</small></div><div class="cards-dashboard">${shortcuts.map(([page,i,label,detail])=>`<button class="card-dashboard" data-action="${page}"><span class="icone-card">${icon(i)}</span><span><strong>${label}</strong><small>${detail}</small></span><span class="atalho-seta">↗</span></button>`).join('')}</div></section>
    <div class="dashboard-detalhes"><section class="dashboard-painel"><div class="secao-cabecalho"><h2>Últimos atendimentos</h2>${button('Ver todos ↗','services','','link-texto')}</div>${recent.length?recent.map(s=>`<div class="atendimento-linha"><span class="atendimento-avatar">${esc(s.client_name.charAt(0))}</span><div class="atendimento-nome"><strong>${esc(s.client_name)}</strong><small>${esc(s.service_name)}</small></div><div class="atendimento-valor"><strong>${money(s.amount)}</strong><small>${dateLabel(s.day)}</small></div></div>`).join(''):`<div class="estado-vazio">${icon('cut')}<strong>Uma nova história começa na cadeira.</strong><p>Registre o primeiro serviço para acompanhar os resultados.</p></div>`}</section>
    <div class="dashboard-lateral"><section class="meta-destaque">${icon('target')}<span class="eyebrow">UM PASSO ALÉM</span><h2>Seu próximo objetivo.</h2><p>Metas claras para cada dia, semana e mês.</p>${button('Acompanhar metas ↗','goals')}</section><section class="dashboard-painel"><div class="secao-cabecalho"><h2>Talentos da casa</h2></div><div class="profissionais">${state.profiles.filter(p=>p.active&&p.role==='barber').map(p=>`<div class="profissional"><span class="avatar">${esc(p.name.charAt(0))}</span><strong>${esc(p.name)}</strong></div>`).join('')||empty('Cadastre sua equipe para começar.')}</div></section></div></div></div>`;
}
async function services(args={},token){
    const range=args.start?args:period('month',state.today);
    app.innerHTML=panel(owner()?'Atendimentos e financeiro':'Meus atendimentos','Consulte serviços, valores e comissões por período.',`<div class="action-row">${button('＋ Registrar serviço','newService','','botao-principal')}${button('Metas','goals')}${owner()?button('Tabela de preços','catalog'):''}</div><div class="botoes-periodo">${['day','week','month'].map((p,i)=>button(['Hoje','Esta semana','Este mês'][i],'period',p)).join('')}</div><form id="reportForm" class="form-grid">${field('start','De','date',range.start,'required')}${field('end','Até','date',range.end,'required')}${owner()?select('barber_id','Profissional',[['','Toda a equipe'],...state.profiles.map(p=>[p.id,p.name])],args.barber_id||''):''}${submit('Consultar')}</form><div id="reportResult" aria-live="polite">${empty('Carregando registros…')}</div>`);
    bindForm('reportForm',async data=>{if(data.start>data.end)throw new Error('A data inicial deve ser anterior à final.');await go('services',data);});
    const rows=await call('report',{...range,barber_id:args.barber_id||''});if(token!==sequence)return;
    $('reportResult').innerHTML=`<p class="hint">Período: ${dateLabel(range.start)} a ${dateLabel(range.end)}${args.barber_id?' · '+esc(state.profiles.find(p=>p.id===args.barber_id)?.name||''):''}</p>`+metrics(rows)+`<details><summary>Resumo por profissional e serviço</summary>${owner()?breakdown(rows,'barber_name','Por profissional'):''}${breakdown(rows,'service_name','Por serviço')}${breakdown(rows,'payment','Por pagamento')}</details><div class="action-row">${button('Exportar CSV','exportReport')}${button('Imprimir relatório','print')}</div>`+serviceRows(rows,true);
    $('reportResult').querySelector('[data-action=exportReport]').onclick=()=>download('atendimentos.csv',csv([['Data','Cliente','Profissional','Serviço','Pagamento','Valor','Comissão','Situação'],...rows.map(s=>[s.day,s.client_name,s.barber_name,s.service_name,s.payment,s.amount,s.commission,s.canceled?'Cancelado':'Confirmado'])]),'text/csv;charset=utf-8');
}
function newService(){
    const clients=state.clients.filter(c=>c.active),profiles=state.profiles.filter(p=>p.active),catalog=state.catalog.filter(c=>c.active);
    app.innerHTML=panel('Registrar serviço','Os preços e a comissão são calculados pelo sistema.',`<form id="serviceForm">${select('client_id','Cliente',[['','Selecione o cliente'],...clients.map(c=>[c.id,c.name+(c.phone?' · '+c.phone:'')])])}${button('Cadastrar um novo cliente','clients','','link-texto')}${owner()?select('barber_id','Profissional',[['','Selecione o profissional'],...profiles.map(p=>[p.id,p.name])]):`<p class="registro">Profissional: <strong>${esc(state.me.name)}</strong></p>`}<fieldset><legend>Serviços realizados</legend><div class="catalog-grid">${catalog.map(c=>`<label class="service-choice"><input type="checkbox" name="catalog_ids" value="${esc(c.id)}"><span>${esc(c.name)}<small>${money(c.price)}</small></span></label>`).join('')}</div></fieldset><p class="service-total">Total <strong id="serviceTotal">${money(0)}</strong></p><div class="form-grid">${field('day','Data do atendimento','date',state.today,`required max="${state.today}" ${owner()?'':`min="${addDays(state.today,-7)}"`}`)}${select('payment','Pagamento',[['','Selecione'],...['Pix','Dinheiro','Cartão','Outro'].map(v=>[v,v])])}</div>${submit('Salvar atendimento')}</form>`);
    $('serviceForm').onchange=()=>{$('serviceTotal').textContent=money([...document.querySelectorAll('[name=catalog_ids]:checked')].reduce((n,input)=>n+Number(catalog.find(c=>c.id===input.value).price),0));};
    const request_id=crypto.randomUUID();
    bindForm('serviceForm',async(data,form)=>{const catalog_ids=new FormData(form).getAll('catalog_ids');if(!data.client_id||!data.payment||!catalog_ids.length||(owner()&&!data.barber_id))throw new Error('Selecione cliente, profissional, serviços e pagamento.');await save('service_add',{...data,catalog_ids,request_id},'services',{start:data.day,end:data.day});});
}
function clients(args={}){
    const editing=state.clients.find(c=>c.id===args.id);
    app.innerHTML=panel('Clientes','Cadastro, retornos e histórico completo de cada cliente.',`<details ${editing?'open':''}><summary>${editing?'Editar cliente':'＋ Cadastrar cliente'}</summary><form id="clientForm">${field('name','Nome completo','text',editing?.name||'','required minlength="2" maxlength="100" autocomplete="name"')}${field('phone','Telefone / WhatsApp (opcional)','tel',editing?.phone||'','maxlength="20" autocomplete="tel"')}<label for="notes">Observações (opcional)</label><textarea id="notes" name="notes" maxlength="2000">${esc(editing?.notes||'')}</textarea>${submit(editing?'Salvar alterações':'Cadastrar cliente')}</form></details><div class="search-row">${field('clientSearch','Pesquisar nome ou telefone','search','','placeholder="Digite para pesquisar…"')}<label class="check-label"><input id="showInactive" type="checkbox"> Incluir arquivados</label></div><div id="clientList"></div><details><summary>Retornos sugeridos · 20 dias</summary><p class="hint">Sugestões com base no último atendimento registrado. Não são agendamentos confirmados.</p><div id="returnList"></div></details>`);
    bindForm('clientForm',data=>save('client_save',{...data,id:editing?.id},'clients'));
    function list(){const q=normalize($('clientSearch').value);const rows=state.clients.filter(c=>(c.active||$('showInactive').checked)&&(normalize(c.name).includes(q)||c.phone.includes(q)));$('clientList').innerHTML=rows.length?rows.map(c=>`<article class="registro"><div class="record-main"><div><strong>${esc(c.name)}${c.active?'':' · Arquivado'}</strong><p>${esc(c.phone||'Sem telefone')}</p><small>Último atendimento: ${dateLabel(c.last_day)}</small></div>${button('Ver histórico ↗','history',c.id,'link-texto')}</div><div class="action-row">${owner()||c.created_by===state.me.id?button('Editar','editClient',c.id,'link-texto'):''}${owner()?button(c.active?'Arquivar':'Reativar','clientActive',c.id,'link-texto'):''}</div></article>`).join(''):empty('Nenhum cliente encontrado.');}
    $('clientSearch').oninput=list;$('showInactive').onchange=list;list();
    const returns=state.clients.filter(c=>c.active&&c.last_day&&addDays(c.last_day,20)<=addDays(state.today,3)).sort((a,b)=>a.last_day.localeCompare(b.last_day));
    $('returnList').innerHTML=returns.map(c=>`<article class="registro"><strong>${esc(c.name)}</strong><p>Retorno sugerido: ${dateLabel(addDays(c.last_day,20))}</p>${button('Consultar histórico','history',c.id,'link-texto')}</article>`).join('')||empty('Nenhum retorno próximo.');
}
async function history(args,token){
    const client=state.clients.find(c=>c.id===args.id);if(!client)throw new Error('Cliente não encontrado.');
    app.innerHTML=panel(client.name,'Histórico de todos os profissionais da barbearia.',empty('Carregando histórico…'));
    const rows=await call('history',{client_id:client.id});if(token!==sequence)return;
    const first=rows.length?rows[rows.length-1].day:'',monthly=[];
    for(let n=11;n>=0;n--){const d=new Date(state.today+'T12:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-n);const key=d.toISOString().slice(0,7);monthly.push([key,rows.filter(s=>s.day.startsWith(key)).reduce((v,s)=>v+Number(s.amount),0)]);}
    app.innerHTML=panel(client.name,client.phone||'Histórico completo do cliente.',`${button('← Voltar aos clientes','clients','','link-texto')}<p class="registro">${esc(client.notes||'Nenhuma observação cadastrada.')}</p><div class="cards"><div class="card"><small>Total de atendimentos</small><strong>${rows.length}</strong></div><div class="card"><small>Total gasto</small><strong>${money(totals(rows).amount)}</strong></div><div class="card"><small>Primeiro atendimento</small><strong>${dateLabel(first)}</strong></div></div>${anniversaryReached(first,state.today)?'<p class="registro retorno-proximo">Cliente com histórico de um ano ou mais.</p>':''}<h3>Gastos nos últimos 12 meses</h3><div class="monthly-grid">${monthly.map(([key,amount])=>`<div><span>${key.slice(5)}/${key.slice(0,4)}</span><strong>${money(amount)}</strong></div>`).join('')}</div><div class="action-row">${button('Exportar histórico CSV','exportHistory')}${button('Imprimir histórico','print')}</div><h3>Todos os serviços realizados</h3>${serviceRows(rows)}`);
    app.querySelector('[data-action=exportHistory]').onclick=()=>download('historico-cliente.csv',csv([['Data','Serviço','Profissional','Pagamento','Valor'],...rows.map(s=>[s.day,s.service_name,s.barber_name,s.payment,s.amount])]),'text/csv;charset=utf-8');
}
function goals(args={}){
    const id=owner()?(args.id||state.me.id):state.me.id,goal=state.goals.find(g=>g.profile_id===id),locked=!owner()&&!!goal,target=state.profiles.find(p=>p.id===id)||state.me;
    const rows=state.services.filter(s=>!s.canceled&&(target.role==='owner'||s.barber_id===id));
    app.innerHTML=panel('Metas do mês',`${state.month.slice(5)}/${state.month.slice(0,4)} · Valores de faturamento em reais.`,`${owner()?select('goalProfile','Consultar metas',state.profiles.filter(p=>p.active).map(p=>[p.id,p.name+(p.role==='owner'?' · barbearia':'')]),id):''}<p class="registro">${locked?'Suas metas estão definidas até o fim deste mês. Novos valores poderão ser escolhidos no mês seguinte.':owner()?'Você pode definir e ajustar as metas da equipe. Os ajustes ficam registrados.':'Defina os três valores juntos. Depois de salvar, eles ficarão fixos até o mês seguinte.'}</p><form id="goalsForm"><div class="goal-grid">${[['daily','Diária','day'],['weekly','Semanal','week'],['monthly','Mensal','month']].map(([key,label,kind])=>{const range=period(kind,state.today),done=totals(rows.filter(s=>s.day>=range.start&&s.day<=range.end)).amount,amount=Number(goal?.[key]||0),pct=amount?Math.min(100,done/amount*100):0;return `<section class="bloco-info"><h3>${label}</h3><p>${dateLabel(range.start)}${range.start!==range.end?' a '+dateLabel(range.end):''}</p><strong>${money(done)}</strong><p>de ${money(amount)}</p><div class="meta-progresso" role="progressbar" aria-label="Meta ${label}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(pct)}"><div class="meta-progresso-barra" style="width:${pct}%"></div></div>${field(key,`Meta ${label.toLowerCase()} (R$)`,'number',goal?.[key]||'','min="0.01" max="1000000" step="0.01" required '+(locked?'disabled':''))}</section>`;}).join('')}</div>${locked?'':submit(goal?'Salvar metas do mês':'Definir metas do mês')}</form>`);
    $('goalProfile')?.addEventListener('change',event=>go('goals',{id:event.target.value}));bindForm('goalsForm',data=>save('goals_save',{...data,profile_id:id},'goals',{id}));
}
function team(args={}){
    const editing=state.profiles.find(p=>p.id===args.id);
    app.innerHTML=panel('Profissionais','Acesso individual e comissão de cada integrante.',`<details ${editing?'open':''}><summary>${editing?'Editar profissional':'＋ Liberar acesso para um barbeiro'}</summary><p class="hint">Após o cadastro, o profissional usa “Primeiro acesso” na tela de entrada com o mesmo e-mail e define a própria senha.</p><form id="profileForm">${field('name','Nome','text',editing?.name||'','required minlength="2" maxlength="100"')}${field('email','E-mail de acesso','email',editing?.email||'','required maxlength="254" '+(editing?'disabled':''))}${field('commission_rate','Comissão (%)','number',editing?.commission_rate??50,'required min="0" max="100" step="0.01"')}${submit(editing?'Salvar profissional':'Liberar acesso')}</form></details><div class="records">${state.profiles.map(p=>`<article class="registro"><div class="record-main"><div><strong>${esc(p.name)}</strong><p>${esc(p.email)}</p><small>${p.role==='owner'?'Dono':'Barbeiro'} · ${p.active?'Ativo':'Desativado'} · Comissão ${p.commission_rate}%</small></div></div><div class="action-row">${button('Editar','editProfile',p.id,'link-texto')}${button('Metas','profileGoals',p.id,'link-texto')}${p.role==='barber'?button(p.active?'Desativar acesso':'Reativar acesso','profileActive',p.id,'link-texto'):''}</div></article>`).join('')}</div>`);
    bindForm('profileForm',data=>save('profile_save',{...data,id:editing?.id},'team'));
}
function catalog(args={}){
    const editing=state.catalog.find(c=>c.id===args.id);
    app.innerHTML=panel('Tabela de preços','Alterações de preço valem apenas para novos atendimentos.',`<form id="catalogForm" class="form-grid">${field('name','Nome do serviço','text',editing?.name||'','required minlength="2" maxlength="100"')}${field('price','Preço (R$)','number',editing?.price||'','required min="0.01" max="1000000" step="0.01"')}${submit(editing?'Salvar preço':'Adicionar serviço')}</form>${state.catalog.map(c=>`<div class="registro record-main"><div><strong>${esc(c.name)}</strong><p>${money(c.price)} · ${c.active?'Ativo':'Desativado'}</p></div><div>${button('Editar','editCatalog',c.id,'link-texto')}${button(c.active?'Desativar':'Ativar','catalogActive',c.id,'link-texto')}</div></div>`).join('')}`);
    bindForm('catalogForm',data=>save('catalog_save',{...data,id:editing?.id,active:editing?.active??true},'catalog'));
}
function localLegacy(){const result={format:'martins-legacy-v1'};for(const key of ['clientes','servicos','barbeiros','metas','conta']){try{result[key]=JSON.parse(localStorage.getItem(key)||'null');}catch{result[key]=null;}}if(Array.isArray(result.barbeiros))result.barbeiros=result.barbeiros.map(p=>typeof p==='string'?{nome:p}:{nome:p.nome});return result;}
function account(){
    app.innerHTML=panel('Minha conta',owner()?'Administrador':state.me.name,`<p class="registro">${esc(state.me.email||'')} · ${owner()?'Dono':'Barbeiro'}</p>${owner()?`<details><summary>Dados da barbearia</summary><form id="shopForm">${field('name','Nome da barbearia','text',state.shop.name,'required minlength="2" maxlength="100"')}${field('phone','Telefone','tel',state.shop.phone,'maxlength="20"')}${field('address','Endereço','text',state.shop.address,'maxlength="300"')}${submit('Salvar dados')}</form></details>`:''}<details ${recovery?'open':''}><summary>Alterar minha senha</summary><form id="passwordForm">${field('newPassword','Nova senha','password','','required minlength="10" autocomplete="new-password"')}${field('confirmPassword','Confirme a senha','password','','required minlength="10" autocomplete="new-password"')}${submit('Alterar senha')}</form></details>${owner()?`<details><summary>Exportação e dados antigos</summary><p class="hint">Exporte os registros periodicamente. O arquivo contém dados de clientes; guarde em local privado.</p>${button('Exportar todos os registros','backup')}${button('Exportar dados da versão antiga neste navegador','legacyExport')}<form id="importForm"><label for="legacyFile">Importar clientes e atendimentos da versão antiga (.json)</label><input id="legacyFile" type="file" accept="application/json,.json" required><p class="hint">Cadastre antes os profissionais com os mesmos nomes. A importação acrescenta dados, preserva os existentes e ignora registros repetidos. Senhas não são importadas. As metas antigas ficam na cópia exportada; defina as metas do novo sistema novamente.</p>${submit('Importar histórico antigo')}</form></details><div class="action-row">${button('Equipe','team')}${button('Tabela de preços','catalog')}${button('Registro de alterações','audit')}</div>`:''}${button('Sair da conta','logout','','botao-excluir')}`);
    bindForm('shopForm',data=>save('settings_save',data,'account'));
    bindForm('passwordForm',async data=>{if(demo)throw new Error('Senhas não são alteradas na demonstração.');if(data.newPassword!==data.confirmPassword)throw new Error('As senhas não coincidem.');const {error}=await cloud.auth.updateUser({password:data.newPassword});if(error)throw error;recovery=false;await cloud.auth.signOut({scope:'global'});showLogin();notify('Senha alterada. Entre novamente com sua nova senha.');});
    bindForm('importForm',async()=>{if(demo)throw new Error('Importação indisponível na demonstração.');const file=$('legacyFile').files[0];if(!file||file.size>10*1024*1024)throw new Error('Selecione um arquivo JSON de até 10 MB.');let data;try{data=JSON.parse(await file.text());}catch{throw new Error('O arquivo JSON não é válido.');}if(!Array.isArray(data.servicos)||!Array.isArray(data.clientes))throw new Error('Selecione a exportação da versão antiga.');const result=await importLegacy(data);await go('account');notify(`Importação concluída: ${result.imported} atendimentos adicionados.`);});
}
async function audit(args,token){const rows=await call('audit');if(token!==sequence)return;const labels={client_save:'Cliente salvo',service_add:'Atendimento registrado',goals_save:'Metas alteradas',profile_save:'Profissional salvo',profile_active:'Acesso do profissional alterado',client_active:'Situação do cliente alterada',catalog_save:'Tabela de preços alterada',service_cancel:'Atendimento cancelado',settings_save:'Dados da barbearia alterados',legacy_import:'Histórico antigo importado'};app.innerHTML=panel('Registro de alterações','Últimas 100 ações administrativas e de cadastro.',rows.map(row=>`<article class="registro"><strong>${esc(labels[row.action]||row.action)}</strong><p>${esc(row.actor_name)} · ${new Date(row.created_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p></article>`).join('')||empty('Nenhuma alteração registrada.'));}

document.addEventListener('click',async event=>{
    const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const {action,id}=el.dataset;
    try{
        if(['home','services','clients','newService','goals','team','catalog','account','audit','history'].includes(action)){await go(action,{id});return;}
        if(action==='period')await go('services',period(id,state.today));
        if(action==='editClient')await go('clients',{id});
        if(action==='editProfile')await go('team',{id});
        if(action==='editCatalog')await go('catalog',{id});
        if(action==='profileGoals')await go('goals',{id});
        if(action==='refresh')await go(route,routeArgs);
        if(action==='print')window.print();
        if(action==='demoRole'){demoRole=demoRole==='owner'?'barber':'owner';await go();}
        if(action==='logout'){if(!demo){const {error}=await cloud.auth.signOut();if(error)throw error;}demo=false;recovery=false;showLogin();notify('Você saiu da conta.');}
        if(action==='backup'){const data=await call('backup');download('martins-registros-'+state.today+'.json',JSON.stringify(data,null,2));notify('Exportação preparada. Guarde o arquivo em local privado.');}
        if(action==='legacyExport'){const data=localLegacy();if(!data.clientes&&!data.servicos)throw new Error('Não há dados antigos neste endereço e navegador. Use a exportação no endereço antigo antes de mudar de endereço.');download('martins-historico-antigo.json',JSON.stringify(data,null,2));}
        if(action==='profileActive'){const p=state.profiles.find(p=>p.id===id);if(!confirm(`${p.active?'Desativar':'Reativar'} acesso de ${p.name}? Os registros serão preservados.`))return;await save('profile_active',{id,active:!p.active},'team');}
        if(action==='clientActive'){const c=state.clients.find(c=>c.id===id);await save('client_active',{id,active:!c.active},'clients');}
        if(action==='catalogActive'){const c=state.catalog.find(c=>c.id===id);await save('catalog_save',{...c,active:!c.active},'catalog');}
        if(action==='cancel'){const reason=prompt('Motivo do cancelamento (mínimo de 5 caracteres). O registro será preservado para auditoria:');if(reason===null)return;await save('service_cancel',{id,reason},'services',routeArgs);}
    }catch(error){notify(errorMessage(error),true);}
});
document.querySelectorAll('[data-page]').forEach(el=>el.onclick=()=>go(el.dataset.page));$('marcaHome').onclick=()=>go();
$('loginForm').onsubmit=async event=>{event.preventDefault();const btn=$('btnEntrar');btn.disabled=true;$('loginErro').textContent='';try{if(!configured)throw new Error('O acesso online ainda precisa ser configurado. Você pode conhecer a demonstração abaixo.');const {error}=await cloud.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginSenha').value});if(error)throw error;$('loginSenha').value='';await go();}catch(error){$('loginErro').textContent=errorMessage(error);}finally{btn.disabled=false;}};
$('firstAccess').onclick=async()=>{if(!configured){$('loginErro').textContent='O acesso online ainda não foi ativado.';return;}if(!$('loginForm').reportValidity())return;$('firstAccess').disabled=true;try{if($('loginSenha').value.length<10)throw new Error('Use pelo menos 10 caracteres para criar sua senha.');const {error}=await cloud.auth.signUp({email:$('loginEmail').value.trim(),password:$('loginSenha').value,options:{emailRedirectTo:new URL('./',location.href).href}});if(error)throw error;$('loginSenha').value='';$('loginErro').textContent='Confira seu e-mail para confirmar o cadastro. O acesso depende de liberação do dono.';}catch(error){$('loginErro').textContent=errorMessage(error);}finally{$('firstAccess').disabled=false;}};
$('forgotPassword').onclick=async()=>{if(!configured){$('loginErro').textContent='O acesso online ainda não foi ativado.';return;}if(!$('loginEmail').reportValidity())return;$('forgotPassword').disabled=true;try{const {error}=await cloud.auth.resetPasswordForEmail($('loginEmail').value.trim(),{redirectTo:new URL('./',location.href).href});if(error)throw error;$('loginErro').textContent='Se houver uma conta para esse e-mail, você receberá as instruções de recuperação.';}catch(error){$('loginErro').textContent=errorMessage(error);}finally{$('forgotPassword').disabled=false;}};
$('openDemo').onclick=()=>{demo=true;demoRole='owner';go();};
window.addEventListener('offline',()=>notify('Sem conexão. Reconecte-se antes de salvar.',true));window.addEventListener('online',()=>notify('Conexão restabelecida. Use Atualizar para buscar os dados mais recentes.'));
async function boot(){
    applyBrand();
    $('setupNotice').hidden=configured;
    if(cloud){cloud.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){recovery=true;setTimeout(()=>go('account'),0);}if(event==='SIGNED_OUT'&&!demo)showLogin();});const {data,error}=await cloud.auth.getSession();if(error)notify(errorMessage(error),true);if(data.session&&!recovery)await go();}
    $('bootMessage').hidden=true;$('loginForm').hidden=false;
}
boot().catch(error=>{notify(errorMessage(error),true);$('bootMessage').hidden=true;$('loginForm').hidden=false;});
